spring:
  ai:
    openai:
      api-key: ${api-key}
      organization-id: ${organization-id}
      project-id: ${project-id}
      chat:
        options:
          model: gpt-4o
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimensions: 1536
      max-document-batch-size: 10000

  datasource:
    url: jdbc:postgresql://localhost:5732/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  sql:
    init:
      data-locations: classpath:sql/init.sql
      mode: always

server:
  port: 9090
